---

- name: Configure GitHub runner
  hosts: local
  become: yes
  vars:
    github_repo_url: ""
    github_runner_name: ""
    github_token: ""
  tasks:
  #### Add runner user
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Create GitHub runner directory
      file:
        path: /home/{{ ansible_user }}/actions-runner
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    
    - name: Run GitHub runner docker container
      docker_container:
        name: github-runner
        image: ghcr.io/actions/actions-runner:latest
        restart_policy: always
        volumes:
          - /home/{{ ansible_user }}/actions-runner:/home/runner/work
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          RUNNER_NAME: "{{ github_runner_name }}"
          REPO_URL: "{{ github_repo_url }}"
          RUNNER_TOKEN: "{{ github_token }}"
      become: true
      
    - name: Show completed message
      debug:
        msg: |
          GitHub runner setup completed successfully!
          - VM ID: {{ hostvars['localhost']['vm_id'] }}
          - VM IP: {{ ansible_host }}
          - GitHub Runner Name: {{ github_runner_name }}